package net.xtrafrancyz.mods.minidot.items.body;

import net.minecraft.client.model.ModelBox;
import net.minecraft.client.model.ModelPlayer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.util.ResourceLocation;
import net.xtrafrancyz.mods.minidot.MiniDotPlayer;
import net.xtrafrancyz.mods.minidot.items.BaseItem;
import net.xtrafrancyz.mods.minidot.items.ItemType;
import net.xtrafrancyz.mods.minidot.items.MModelRenderer;
import net.xtrafrancyz.mods.minidot.items.animation.BBAnimationLoader;
import net.xtrafrancyz.mods.minidot.items.animation.IAnimation;

public class TargetBody extends BaseItem
{
    private final MModelRenderer target;
    private final MModelRenderer op;
    private final MModelRenderer op_two;
    private final MModelRenderer op_one;
    private final MModelRenderer Display;
    private final MModelRenderer E;
    private final MModelRenderer M_m;
    private final MModelRenderer T;
    private final MModelRenderer I;
    private final MModelRenderer H;
    private final MModelRenderer m;
    private final MModelRenderer Light_five;
    private final MModelRenderer Light_five_off;
    private final MModelRenderer Light_five_on;
    private final MModelRenderer Light_four;
    private final MModelRenderer Light_four_off;
    private final MModelRenderer Light_four_on;
    private final MModelRenderer Light_three;
    private final MModelRenderer Light_three_off;
    private final MModelRenderer Light_three_on;
    private final MModelRenderer Light_one;
    private final MModelRenderer Light_one_off;
    private final MModelRenderer Light_one_on;
    private final MModelRenderer Light_two;
    private final MModelRenderer Light_two_off;
    private final MModelRenderer Light_two_on;
    private final MModelRenderer Light_six;
    private final MModelRenderer Light_six_off;
    private final MModelRenderer Light_six_on;
    private final MModelRenderer Light_seven;
    private final MModelRenderer Light_seven_off;
    private final MModelRenderer Light_seven_on;
    private final MModelRenderer Light_eight;
    private final MModelRenderer Light_eight_off;
    private final MModelRenderer Light_eight_on;
    private final MModelRenderer Light_nine;
    private final MModelRenderer Light_nine_off;
    private final MModelRenderer Light_nine_on;
    private final MModelRenderer Light_ten;
    private final MModelRenderer Light_ten_off;
    private final MModelRenderer Light_ten_on;
    private final MModelRenderer arrow_one;
    private final MModelRenderer point;
    private final MModelRenderer Light_point_six;
    private final MModelRenderer Light_point_six_off;
    private final MModelRenderer Light_point_six_on;
    private final MModelRenderer Light_point_four;
    private final MModelRenderer Light_point_four_off;
    private final MModelRenderer Light_point_four_on;
    private final MModelRenderer Light_point_five;
    private final MModelRenderer Light_point_five_off;
    private final MModelRenderer Light_point_five_on;
    private final MModelRenderer arrow_two;
    private final MModelRenderer point_two;
    private final MModelRenderer Light_point_three;
    private final MModelRenderer Light_point_three_off;
    private final MModelRenderer Light_point_three_on;
    private final MModelRenderer Light_point_two;
    private final MModelRenderer Light_point_two_off;
    private final MModelRenderer Light_point_two_on;
    private final MModelRenderer Light_point_one;
    private final MModelRenderer Light_point_one_off;
    private final MModelRenderer Light_point_one_on;
    private final IAnimation animation;

    public TargetBody()
    {
        super(ItemType.BODY);
        this.textureWidth = 128;
        this.textureHeight = 128;
        this.target = new MModelRenderer(this);
        this.target.setRotationPoint(0.0F, -14.0F, 0.0F);
        this.op = new MModelRenderer(this);
        this.op.setRotationPoint(0.0F, 14.0F, 14.0F);
        this.target.addChild(this.op);
        this.op_two = new MModelRenderer(this);
        this.op_two.setRotationPoint(-4.5F, -26.0F, -11.5F);
        this.op.addChild(this.op_two);
        this.op_two.cubeList.add(new ModelBox(this.op_two, 0, 0, 0.5F, 0.0F, -0.5F, 1, 2, 1, 0.0F, false));
        this.op_one = new MModelRenderer(this);
        this.op_one.setRotationPoint(4.5F, -26.0F, -11.5F);
        this.op.addChild(this.op_one);
        this.op_one.cubeList.add(new ModelBox(this.op_one, 0, 0, -1.5F, 0.0F, -0.5F, 1, 2, 1, 0.0F, false));
        this.Display = new MModelRenderer(this);
        this.Display.setRotationPoint(0.0F, -4.0F, -2.5F);
        this.target.addChild(this.Display);
        this.Display.cubeList.add(new ModelBox(this.Display, 0, 21, -27.0F, -7.0F, -1.2F, 55, 14, 1, 0.0F, false));
        this.Display.cubeList.add(new ModelBox(this.Display, 0, 36, -27.0F, -8.0F, -2.0F, 55, 1, 5, 0.0F, false));
        this.Display.cubeList.add(new ModelBox(this.Display, 0, 36, -27.0F, -8.0F, -2.0F, 55, 1, 5, 0.0F, false));
        this.Display.cubeList.add(new ModelBox(this.Display, 0, 0, -28.0F, 7.0F, -2.0F, 57, 1, 5, 0.0F, false));
        this.Display.cubeList.add(new ModelBox(this.Display, 12, 55, 28.0F, -8.0F, -2.0F, 1, 15, 5, 0.0F, false));
        this.Display.cubeList.add(new ModelBox(this.Display, 0, 55, -28.0F, -8.0F, -2.0F, 1, 15, 5, 0.0F, false));
        this.Display.cubeList.add(new ModelBox(this.Display, 0, 6, -27.0F, -7.0F, 3.0F, 55, 14, 1, 0.0F, false));
        this.E = new MModelRenderer(this);
        this.Display.addChild(this.E);
        this.E.cubeList.add(new ModelBox(this.E, 54, 42, 17.0F, -6.0F, -1.4F, 10, 12, 0, 0.0F, false));
        this.M_m = new MModelRenderer(this);
        this.Display.addChild(this.M_m);
        this.M_m.cubeList.add(new ModelBox(this.M_m, 30, 42, 4.0F, -6.0F, -1.4F, 12, 12, 0, 0.0F, false));
        this.T = new MModelRenderer(this);
        this.T.setRotationPoint(-1.0F, 18.0F, 3.5F);
        this.Display.addChild(this.T);
        this.T.cubeList.add(new ModelBox(this.T, 30, 54, -9.0F, -25.0F, -4.8F, 10, 13, 0, 0.0F, false));
        this.I = new MModelRenderer(this);
        this.I.setRotationPoint(-1.0F, 18.0F, 3.5F);
        this.Display.addChild(this.I);
        this.I.cubeList.add(new ModelBox(this.I, 40, 67, -14.0F, -24.0F, -4.8F, 4, 12, 0, 0.0F, false));
        this.H = new MModelRenderer(this);
        this.H.setRotationPoint(4.2F, 4.7F, 6.0F);
        this.Display.addChild(this.H);
        this.H.cubeList.add(new ModelBox(this.H, 50, 54, -30.2F, -10.7F, -7.3F, 10, 12, 0, 0.0F, false));
        this.m = new MModelRenderer(this);
        this.m.setRotationPoint(0.0F, -4.0F, 1.5F);
        this.target.addChild(this.m);
        this.m.cubeList.add(new ModelBox(this.m, 48, 66, -3.0F, -7.0F, -0.5F, 6, 14, 2, 0.0F, false));
        this.m.cubeList.add(new ModelBox(this.m, 74, 42, 6.0F, -3.0F, -0.5F, 1, 6, 2, 0.0F, false));
        this.m.cubeList.add(new ModelBox(this.m, 0, 75, 6.0F, -3.0F, -0.5F, 1, 6, 1, 0.0F, false));
        this.m.cubeList.add(new ModelBox(this.m, 24, 55, -7.0F, -3.0F, -0.5F, 1, 6, 2, 0.0F, false));
        this.m.cubeList.add(new ModelBox(this.m, 72, 66, 5.0F, -5.0F, -0.5F, 1, 10, 2, 0.0F, false));
        this.m.cubeList.add(new ModelBox(this.m, 70, 54, -6.0F, -5.0F, -0.5F, 1, 10, 2, 0.0F, false));
        this.m.cubeList.add(new ModelBox(this.m, 32, 67, 3.0F, -6.0F, -0.5F, 2, 12, 2, 0.0F, false));
        this.m.cubeList.add(new ModelBox(this.m, 24, 65, -5.0F, -6.0F, -0.5F, 2, 12, 2, 0.0F, false));
        this.Light_five = new MModelRenderer(this);
        this.Light_five.setRotationPoint(2.5F, 7.0F, -1.0F);
        this.m.addChild(this.Light_five);
        this.Light_five_off = new MModelRenderer(this);
        this.Light_five_off.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Light_five.addChild(this.Light_five_off);
        this.Light_five_off.cubeList.add(new ModelBox(this.Light_five_off, 0, 36, -0.5F, -0.5F, -0.5F, 1, 1, 1, 0.2F, false));
        this.Light_five_on = new MModelRenderer(this);
        this.Light_five_on.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Light_five.addChild(this.Light_five_on);
        this.Light_five_on.cubeList.add(new ModelBox(this.Light_five_on, 0, 3, -0.5F, -0.5F, -0.5F, 1, 1, 1, 0.2F, false));
        this.Light_four = new MModelRenderer(this);
        this.Light_four.setRotationPoint(-2.5F, 7.0F, -1.0F);
        this.m.addChild(this.Light_four);
        this.Light_four_off = new MModelRenderer(this);
        this.Light_four_off.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Light_four.addChild(this.Light_four_off);
        this.Light_four_off.cubeList.add(new ModelBox(this.Light_four_off, 0, 36, -0.5F, -0.5F, -0.5F, 1, 1, 1, 0.2F, false));
        this.Light_four_on = new MModelRenderer(this);
        this.Light_four_on.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Light_four.addChild(this.Light_four_on);
        this.Light_four_on.cubeList.add(new ModelBox(this.Light_four_on, 0, 3, -0.5F, -0.5F, -0.5F, 1, 1, 1, 0.2F, false));
        this.Light_three = new MModelRenderer(this);
        this.Light_three.setRotationPoint(-5.5F, 5.0F, -1.0F);
        this.m.addChild(this.Light_three);
        this.Light_three_off = new MModelRenderer(this);
        this.Light_three_off.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Light_three.addChild(this.Light_three_off);
        this.Light_three_off.cubeList.add(new ModelBox(this.Light_three_off, 0, 36, -0.5F, -0.5F, -0.5F, 1, 1, 1, 0.2F, false));
        this.Light_three_on = new MModelRenderer(this);
        this.Light_three_on.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Light_three.addChild(this.Light_three_on);
        this.Light_three_on.cubeList.add(new ModelBox(this.Light_three_on, 0, 3, -0.5F, -0.5F, -0.5F, 1, 1, 1, 0.2F, false));
        this.Light_one = new MModelRenderer(this);
        this.Light_one.setRotationPoint(-7.0F, -2.0F, -1.0F);
        this.m.addChild(this.Light_one);
        this.Light_one_off = new MModelRenderer(this);
        this.Light_one_off.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Light_one.addChild(this.Light_one_off);
        this.Light_one_off.cubeList.add(new ModelBox(this.Light_one_off, 0, 36, -0.5F, -0.5F, -0.5F, 1, 1, 1, 0.2F, false));
        this.Light_one_on = new MModelRenderer(this);
        this.Light_one_on.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Light_one.addChild(this.Light_one_on);
        this.Light_one_on.cubeList.add(new ModelBox(this.Light_one_on, 0, 3, -0.5F, -0.5F, -0.5F, 1, 1, 1, 0.2F, false));
        this.Light_two = new MModelRenderer(this);
        this.Light_two.setRotationPoint(-7.0F, 2.0F, -1.0F);
        this.m.addChild(this.Light_two);
        this.Light_two_off = new MModelRenderer(this);
        this.Light_two_off.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Light_two.addChild(this.Light_two_off);
        this.Light_two_off.cubeList.add(new ModelBox(this.Light_two_off, 0, 36, -0.5F, -0.5F, -0.5F, 1, 1, 1, 0.2F, false));
        this.Light_two_on = new MModelRenderer(this);
        this.Light_two_on.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Light_two.addChild(this.Light_two_on);
        this.Light_two_on.cubeList.add(new ModelBox(this.Light_two_on, 0, 3, -0.5F, -0.5F, -0.5F, 1, 1, 1, 0.2F, false));
        this.Light_six = new MModelRenderer(this);
        this.Light_six.setRotationPoint(5.5F, 5.0F, -1.0F);
        this.m.addChild(this.Light_six);
        this.Light_six_off = new MModelRenderer(this);
        this.Light_six_off.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Light_six.addChild(this.Light_six_off);
        this.Light_six_off.cubeList.add(new ModelBox(this.Light_six_off, 0, 36, -0.5F, -0.5F, -0.5F, 1, 1, 1, 0.2F, false));
        this.Light_six_on = new MModelRenderer(this);
        this.Light_six_on.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Light_six.addChild(this.Light_six_on);
        this.Light_six_on.cubeList.add(new ModelBox(this.Light_six_on, 0, 3, -0.5F, -0.5F, -0.5F, 1, 1, 1, 0.2F, false));
        this.Light_seven = new MModelRenderer(this);
        this.Light_seven.setRotationPoint(7.0F, 2.0F, -1.0F);
        this.m.addChild(this.Light_seven);
        this.Light_seven_off = new MModelRenderer(this);
        this.Light_seven_off.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Light_seven.addChild(this.Light_seven_off);
        this.Light_seven_off.cubeList.add(new ModelBox(this.Light_seven_off, 0, 36, -0.5F, -0.5F, -0.5F, 1, 1, 1, 0.2F, false));
        this.Light_seven_on = new MModelRenderer(this);
        this.Light_seven_on.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Light_seven.addChild(this.Light_seven_on);
        this.Light_seven_on.cubeList.add(new ModelBox(this.Light_seven_on, 0, 3, -0.5F, -0.5F, -0.5F, 1, 1, 1, 0.2F, false));
        this.Light_eight = new MModelRenderer(this);
        this.Light_eight.setRotationPoint(7.0F, -2.0F, -1.0F);
        this.m.addChild(this.Light_eight);
        this.Light_eight_off = new MModelRenderer(this);
        this.Light_eight_off.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Light_eight.addChild(this.Light_eight_off);
        this.Light_eight_off.cubeList.add(new ModelBox(this.Light_eight_off, 0, 36, -0.5F, -0.5F, -0.5F, 1, 1, 1, 0.2F, false));
        this.Light_eight_on = new MModelRenderer(this);
        this.Light_eight_on.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Light_eight.addChild(this.Light_eight_on);
        this.Light_eight_on.cubeList.add(new ModelBox(this.Light_eight_on, 0, 3, -0.5F, -0.5F, -0.5F, 1, 1, 1, 0.2F, false));
        this.Light_nine = new MModelRenderer(this);
        this.Light_nine.setRotationPoint(-5.0F, -5.5F, -1.0F);
        this.m.addChild(this.Light_nine);
        this.Light_nine_off = new MModelRenderer(this);
        this.Light_nine_off.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Light_nine.addChild(this.Light_nine_off);
        this.Light_nine_off.cubeList.add(new ModelBox(this.Light_nine_off, 0, 36, -0.5F, -0.5F, -0.5F, 1, 1, 1, 0.2F, false));
        this.Light_nine_on = new MModelRenderer(this);
        this.Light_nine_on.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Light_nine.addChild(this.Light_nine_on);
        this.Light_nine_on.cubeList.add(new ModelBox(this.Light_nine_on, 0, 3, -0.5F, -0.5F, -0.5F, 1, 1, 1, 0.2F, false));
        this.Light_ten = new MModelRenderer(this);
        this.Light_ten.setRotationPoint(5.0F, -5.5F, -1.0F);
        this.m.addChild(this.Light_ten);
        this.Light_ten_off = new MModelRenderer(this);
        this.Light_ten_off.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Light_ten.addChild(this.Light_ten_off);
        this.Light_ten_off.cubeList.add(new ModelBox(this.Light_ten_off, 0, 36, -0.5F, -0.5F, -0.5F, 1, 1, 1, 0.2F, false));
        this.Light_ten_on = new MModelRenderer(this);
        this.Light_ten_on.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Light_ten.addChild(this.Light_ten_on);
        this.Light_ten_on.cubeList.add(new ModelBox(this.Light_ten_on, 0, 3, -0.5F, -0.5F, -0.5F, 1, 1, 1, 0.2F, false));
        this.arrow_one = new MModelRenderer(this);
        this.arrow_one.setRotationPoint(3.1F, 8.5F, -3.1F);
        this.setRotation(this.arrow_one, -0.8775F, 0.0309F, -0.4906F);
        this.m.addChild(this.arrow_one);
        this.arrow_one.cubeList.add(new ModelBox(this.arrow_one, 64, 66, 0.5F, -6.5F, 0.5F, 3, 13, 1, 0.0F, false));
        this.point = new MModelRenderer(this);
        this.point.setRotationPoint(2.0F, 6.5F, 0.5F);
        this.arrow_one.addChild(this.point);
        this.point.cubeList.add(new ModelBox(this.point, 0, 42, -10.0F, -6.5F, -0.1F, 15, 13, 0, 0.0F, false));
        this.Light_point_six = new MModelRenderer(this);
        this.Light_point_six.setRotationPoint(-3.4F, 6.3F, 0.0F);
        this.point.addChild(this.Light_point_six);
        this.Light_point_six_off = new MModelRenderer(this);
        this.Light_point_six_off.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Light_point_six.addChild(this.Light_point_six_off);
        this.Light_point_six_off.cubeList.add(new ModelBox(this.Light_point_six_off, 0, 36, -0.5F, -0.5F, -0.5F, 1, 1, 1, 0.2F, false));
        this.Light_point_six_on = new MModelRenderer(this);
        this.Light_point_six_on.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Light_point_six.addChild(this.Light_point_six_on);
        this.Light_point_six_on.cubeList.add(new ModelBox(this.Light_point_six_on, 0, 3, -0.5F, -0.5F, -0.5F, 1, 1, 1, 0.2F, false));
        this.Light_point_four = new MModelRenderer(this);
        this.Light_point_four.setRotationPoint(-9.4F, -0.1F, -0.2F);
        this.point.addChild(this.Light_point_four);
        this.Light_point_four_off = new MModelRenderer(this);
        this.Light_point_four_off.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Light_point_four.addChild(this.Light_point_four_off);
        this.Light_point_four_off.cubeList.add(new ModelBox(this.Light_point_four_off, 0, 36, -0.5F, -0.5F, -0.5F, 1, 1, 1, 0.2F, false));
        this.Light_point_four_on = new MModelRenderer(this);
        this.Light_point_four_on.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Light_point_four.addChild(this.Light_point_four_on);
        this.Light_point_four_on.cubeList.add(new ModelBox(this.Light_point_four_on, 0, 3, -0.5F, -0.5F, -0.5F, 1, 1, 1, 0.2F, false));
        this.Light_point_five = new MModelRenderer(this);
        this.Light_point_five.setRotationPoint(-3.4F, -6.3F, 0.0F);
        this.point.addChild(this.Light_point_five);
        this.Light_point_five_off = new MModelRenderer(this);
        this.Light_point_five_off.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Light_point_five.addChild(this.Light_point_five_off);
        this.Light_point_five_off.cubeList.add(new ModelBox(this.Light_point_five_off, 0, 36, -0.5F, -0.5F, -0.5F, 1, 1, 1, 0.2F, false));
        this.Light_point_five_on = new MModelRenderer(this);
        this.Light_point_five_on.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Light_point_five.addChild(this.Light_point_five_on);
        this.Light_point_five_on.cubeList.add(new ModelBox(this.Light_point_five_on, 0, 3, -0.5F, -0.5F, -0.5F, 1, 1, 1, 0.2F, false));
        this.arrow_two = new MModelRenderer(this);
        this.arrow_two.setRotationPoint(-6.9F, 8.0F, -2.2F);
        this.setRotation(this.arrow_two, -0.5196F, 0.0017F, 0.5585F);
        this.m.addChild(this.arrow_two);
        this.arrow_two.cubeList.add(new ModelBox(this.arrow_two, 64, 66, 0.5F, -6.5F, 0.5F, 3, 13, 1, 0.0F, false));
        this.point_two = new MModelRenderer(this);
        this.point_two.setRotationPoint(2.0F, 6.5F, 0.5F);
        this.arrow_two.addChild(this.point_two);
        this.point_two.cubeList.add(new ModelBox(this.point_two, 0, 42, -10.0F, -6.5F, -0.1F, 15, 13, 0, 0.0F, false));
        this.Light_point_three = new MModelRenderer(this);
        this.Light_point_three.setRotationPoint(-3.4F, 6.3F, -0.3F);
        this.point_two.addChild(this.Light_point_three);
        this.Light_point_three_off = new MModelRenderer(this);
        this.Light_point_three_off.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Light_point_three.addChild(this.Light_point_three_off);
        this.Light_point_three_off.cubeList.add(new ModelBox(this.Light_point_three_off, 0, 36, -0.5F, -0.5F, -0.5F, 1, 1, 1, 0.2F, false));
        this.Light_point_three_on = new MModelRenderer(this);
        this.Light_point_three_on.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Light_point_three.addChild(this.Light_point_three_on);
        this.Light_point_three_on.cubeList.add(new ModelBox(this.Light_point_three_on, 0, 3, -0.5F, -0.5F, -0.5F, 1, 1, 1, 0.2F, false));
        this.Light_point_two = new MModelRenderer(this);
        this.Light_point_two.setRotationPoint(-3.4F, -6.3F, -0.3F);
        this.point_two.addChild(this.Light_point_two);
        this.Light_point_two_off = new MModelRenderer(this);
        this.Light_point_two_off.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Light_point_two.addChild(this.Light_point_two_off);
        this.Light_point_two_off.cubeList.add(new ModelBox(this.Light_point_two_off, 0, 36, -0.5F, -0.5F, -0.5F, 1, 1, 1, 0.2F, false));
        this.Light_point_two_on = new MModelRenderer(this);
        this.Light_point_two_on.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Light_point_two.addChild(this.Light_point_two_on);
        this.Light_point_two_on.cubeList.add(new ModelBox(this.Light_point_two_on, 0, 3, -0.5F, -0.5F, -0.5F, 1, 1, 1, 0.2F, false));
        this.Light_point_one = new MModelRenderer(this);
        this.Light_point_one.setRotationPoint(-9.9F, -0.1F, -0.3F);
        this.point_two.addChild(this.Light_point_one);
        this.Light_point_one_off = new MModelRenderer(this);
        this.Light_point_one_off.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Light_point_one.addChild(this.Light_point_one_off);
        this.Light_point_one_off.cubeList.add(new ModelBox(this.Light_point_one_off, 0, 36, -0.5F, -0.5F, -0.5F, 1, 1, 1, 0.2F, false));
        this.Light_point_one_on = new MModelRenderer(this);
        this.Light_point_one_on.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Light_point_one.addChild(this.Light_point_one_on);
        this.Light_point_one_on.cubeList.add(new ModelBox(this.Light_point_one_on, 0, 3, -0.5F, -0.5F, -0.5F, 1, 1, 1, 0.2F, false));
        super.setTexture(new ResourceLocation("minidot", "body/targetbody.png"));
        BBAnimationLoader bbanimationloader = new BBAnimationLoader(new ResourceLocation("minidot", "body/targetbody_animation.json"));
        this.animation = bbanimationloader.mustGet("targetbody.animation", this);
    }

    protected void preRender(ModelPlayer modelPlayer, EntityPlayer player, float time, MiniDotPlayer pi)
    {
        super.preRender(modelPlayer, player, time, pi);
        this.animation.tick(time);
        GlStateManager.translate(0.0D, 1.52D, -0.34D - (player.inventory.armorItemInSlot(2) != null ? 0.1D : 0.0D));
    }

    public void renderAsItem(float time)
    {
        this.animation.tick(time);
        double d0 = 1.3D;
        GlStateManager.scale(d0, d0, d0);
        GlStateManager.translate(0.0D, 1.1199999999999999D, 0.21D);
        super.renderAsItem(time);
    }

    public void render(ModelPlayer modelPlayer, EntityPlayer player, float time, MiniDotPlayer pi)
    {
        GlStateManager.enableCull();
        super.render(modelPlayer, player, time, pi);
        GlStateManager.disableCull();
    }

    public String getName()
    {
        return "\u041c\u0438\u0448\u0435\u043d\u044c";
    }

    public String getCreator()
    {
        return "NovikoV1337 & Sir_Kelt";
    }
}
