package net.xtrafrancyz.mods.minidot.items;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import net.xtrafrancyz.mods.minidot.MiniDot;
import net.xtrafrancyz.mods.minidot.items.body.AncientHammer;
import net.xtrafrancyz.mods.minidot.items.body.BackPack;
import net.xtrafrancyz.mods.minidot.items.body.BatWings;
import net.xtrafrancyz.mods.minidot.items.body.BatterflyWings;
import net.xtrafrancyz.mods.minidot.items.body.BatterflyWingsV2;
import net.xtrafrancyz.mods.minidot.items.body.BigWings;
import net.xtrafrancyz.mods.minidot.items.body.BloodyAxe;
import net.xtrafrancyz.mods.minidot.items.body.BodyFlower;
import net.xtrafrancyz.mods.minidot.items.body.Butterfly23;
import net.xtrafrancyz.mods.minidot.items.body.ButterflyWings;
import net.xtrafrancyz.mods.minidot.items.body.CandyWings;
import net.xtrafrancyz.mods.minidot.items.body.Cauldron;
import net.xtrafrancyz.mods.minidot.items.body.DemonicWings;
import net.xtrafrancyz.mods.minidot.items.body.DogBackpack;
import net.xtrafrancyz.mods.minidot.items.body.DraculasCloak;
import net.xtrafrancyz.mods.minidot.items.body.DroneWings;
import net.xtrafrancyz.mods.minidot.items.body.ExoWings;
import net.xtrafrancyz.mods.minidot.items.body.FallenWings;
import net.xtrafrancyz.mods.minidot.items.body.FieryWings;
import net.xtrafrancyz.mods.minidot.items.body.FireTubes;
import net.xtrafrancyz.mods.minidot.items.body.FirstWings;
import net.xtrafrancyz.mods.minidot.items.body.Garlands;
import net.xtrafrancyz.mods.minidot.items.body.HikingBackpack;
import net.xtrafrancyz.mods.minidot.items.body.HogwartsScarf;
import net.xtrafrancyz.mods.minidot.items.body.InflatableRingUnicorn;
import net.xtrafrancyz.mods.minidot.items.body.IronChains;
import net.xtrafrancyz.mods.minidot.items.body.JetPack;
import net.xtrafrancyz.mods.minidot.items.body.Katana;
import net.xtrafrancyz.mods.minidot.items.body.KleeBackpack;
import net.xtrafrancyz.mods.minidot.items.body.LifeVest;
import net.xtrafrancyz.mods.minidot.items.body.Lifebuoy;
import net.xtrafrancyz.mods.minidot.items.body.LuckyBowTie;
import net.xtrafrancyz.mods.minidot.items.body.MechanicalWings;
import net.xtrafrancyz.mods.minidot.items.body.MercyWings;
import net.xtrafrancyz.mods.minidot.items.body.Mittens;
import net.xtrafrancyz.mods.minidot.items.body.NeonWings;
import net.xtrafrancyz.mods.minidot.items.body.Peacock;
import net.xtrafrancyz.mods.minidot.items.body.PetBackpack;
import net.xtrafrancyz.mods.minidot.items.body.Piglin;
import net.xtrafrancyz.mods.minidot.items.body.Quiver;
import net.xtrafrancyz.mods.minidot.items.body.Scarf;
import net.xtrafrancyz.mods.minidot.items.body.Scythe;
import net.xtrafrancyz.mods.minidot.items.body.SkyeyWings;
import net.xtrafrancyz.mods.minidot.items.body.Snowboard;
import net.xtrafrancyz.mods.minidot.items.body.TargetBody;
import net.xtrafrancyz.mods.minidot.items.body.Tentacles;
import net.xtrafrancyz.mods.minidot.items.body.Trident;
import net.xtrafrancyz.mods.minidot.items.body.WhiteAngelWings;
import net.xtrafrancyz.mods.minidot.items.body.WingsDragon;
import net.xtrafrancyz.mods.minidot.items.head.AntmanHelm;
import net.xtrafrancyz.mods.minidot.items.head.AnvilHat;
import net.xtrafrancyz.mods.minidot.items.head.ArrowHat;
import net.xtrafrancyz.mods.minidot.items.head.AsianHat;
import net.xtrafrancyz.mods.minidot.items.head.BatHat;
import net.xtrafrancyz.mods.minidot.items.head.BearHat;
import net.xtrafrancyz.mods.minidot.items.head.BearsEarsHat;
import net.xtrafrancyz.mods.minidot.items.head.BeaverHat;
import net.xtrafrancyz.mods.minidot.items.head.BobFettaHelm;
import net.xtrafrancyz.mods.minidot.items.head.BoneEarsHat;
import net.xtrafrancyz.mods.minidot.items.head.BrainSlug;
import net.xtrafrancyz.mods.minidot.items.head.BuilderHat;
import net.xtrafrancyz.mods.minidot.items.head.BunnyHat;
import net.xtrafrancyz.mods.minidot.items.head.BunnyHelm;
import net.xtrafrancyz.mods.minidot.items.head.BunnyPanama;
import net.xtrafrancyz.mods.minidot.items.head.ButterflyHat;
import net.xtrafrancyz.mods.minidot.items.head.CakeHat;
import net.xtrafrancyz.mods.minidot.items.head.ChessBoard;
import net.xtrafrancyz.mods.minidot.items.head.ChickenHat;
import net.xtrafrancyz.mods.minidot.items.head.ChristmasHat;
import net.xtrafrancyz.mods.minidot.items.head.ChristmasHat2;
import net.xtrafrancyz.mods.minidot.items.head.ChristmasNose;
import net.xtrafrancyz.mods.minidot.items.head.ClownHat;
import net.xtrafrancyz.mods.minidot.items.head.CoffeeHat;
import net.xtrafrancyz.mods.minidot.items.head.CrabCrown;
import net.xtrafrancyz.mods.minidot.items.head.CreeperHat;
import net.xtrafrancyz.mods.minidot.items.head.CrownIceKingHat;
import net.xtrafrancyz.mods.minidot.items.head.CyborgHat;
import net.xtrafrancyz.mods.minidot.items.head.DealWithItHat;
import net.xtrafrancyz.mods.minidot.items.head.DeerHornsCurvedHat;
import net.xtrafrancyz.mods.minidot.items.head.DeerHornsHat;
import net.xtrafrancyz.mods.minidot.items.head.DevilHorns;
import net.xtrafrancyz.mods.minidot.items.head.Diadem;
import net.xtrafrancyz.mods.minidot.items.head.DjangoFettaHelm;
import net.xtrafrancyz.mods.minidot.items.head.DogEarsHat;
import net.xtrafrancyz.mods.minidot.items.head.DollarGlasses;
import net.xtrafrancyz.mods.minidot.items.head.ElectricHornsHat;
import net.xtrafrancyz.mods.minidot.items.head.ElfEars;
import net.xtrafrancyz.mods.minidot.items.head.ElfHat;
import net.xtrafrancyz.mods.minidot.items.head.FaceHugger;
import net.xtrafrancyz.mods.minidot.items.head.FallenAngelNimbus;
import net.xtrafrancyz.mods.minidot.items.head.FezHat;
import net.xtrafrancyz.mods.minidot.items.head.FireGlasses;
import net.xtrafrancyz.mods.minidot.items.head.FlowersHat;
import net.xtrafrancyz.mods.minidot.items.head.FoxEarsHat;
import net.xtrafrancyz.mods.minidot.items.head.FrogHelm;
import net.xtrafrancyz.mods.minidot.items.head.GeneralRuffsCap;
import net.xtrafrancyz.mods.minidot.items.head.GlassHat;
import net.xtrafrancyz.mods.minidot.items.head.Glasses;
import net.xtrafrancyz.mods.minidot.items.head.HairKnot;
import net.xtrafrancyz.mods.minidot.items.head.HairPinFlowers;
import net.xtrafrancyz.mods.minidot.items.head.HamsterHat;
import net.xtrafrancyz.mods.minidot.items.head.HatterHat;
import net.xtrafrancyz.mods.minidot.items.head.HeadSprout;
import net.xtrafrancyz.mods.minidot.items.head.HeadStarsHat;
import net.xtrafrancyz.mods.minidot.items.head.Headphones;
import net.xtrafrancyz.mods.minidot.items.head.HeartHat;
import net.xtrafrancyz.mods.minidot.items.head.HelicopterHat;
import net.xtrafrancyz.mods.minidot.items.head.HelmetCovid19;
import net.xtrafrancyz.mods.minidot.items.head.HelmetEagle;
import net.xtrafrancyz.mods.minidot.items.head.HelmetFlash;
import net.xtrafrancyz.mods.minidot.items.head.HelmetMouse;
import net.xtrafrancyz.mods.minidot.items.head.HelmetPubg;
import net.xtrafrancyz.mods.minidot.items.head.HelmetSamurai;
import net.xtrafrancyz.mods.minidot.items.head.HelmetTank;
import net.xtrafrancyz.mods.minidot.items.head.HelmetVillager;
import net.xtrafrancyz.mods.minidot.items.head.HelmetZombie;
import net.xtrafrancyz.mods.minidot.items.head.HolographicIroquois;
import net.xtrafrancyz.mods.minidot.items.head.Hood;
import net.xtrafrancyz.mods.minidot.items.head.HornsHat;
import net.xtrafrancyz.mods.minidot.items.head.HornsHead;
import net.xtrafrancyz.mods.minidot.items.head.HutaoHat;
import net.xtrafrancyz.mods.minidot.items.head.HypnoGlasses;
import net.xtrafrancyz.mods.minidot.items.head.IceHat;
import net.xtrafrancyz.mods.minidot.items.head.IndianaJonesHat;
import net.xtrafrancyz.mods.minidot.items.head.KiwiHat;
import net.xtrafrancyz.mods.minidot.items.head.LaserHat;
import net.xtrafrancyz.mods.minidot.items.head.LokiHelmet;
import net.xtrafrancyz.mods.minidot.items.head.MagicianHat;
import net.xtrafrancyz.mods.minidot.items.head.MandalorianHelm;
import net.xtrafrancyz.mods.minidot.items.head.MarioHat;
import net.xtrafrancyz.mods.minidot.items.head.MarvelScarletTiara;
import net.xtrafrancyz.mods.minidot.items.head.MayaHat;
import net.xtrafrancyz.mods.minidot.items.head.MinerHat;
import net.xtrafrancyz.mods.minidot.items.head.Monocle;
import net.xtrafrancyz.mods.minidot.items.head.MoustacheGlasses;
import net.xtrafrancyz.mods.minidot.items.head.Mustache;
import net.xtrafrancyz.mods.minidot.items.head.Muzzle;
import net.xtrafrancyz.mods.minidot.items.head.Nimbus;
import net.xtrafrancyz.mods.minidot.items.head.NinjaHeadband;
import net.xtrafrancyz.mods.minidot.items.head.NvgHat;
import net.xtrafrancyz.mods.minidot.items.head.OniHat;
import net.xtrafrancyz.mods.minidot.items.head.PanamaHat;
import net.xtrafrancyz.mods.minidot.items.head.PandaHat;
import net.xtrafrancyz.mods.minidot.items.head.Peepers;
import net.xtrafrancyz.mods.minidot.items.head.PenguinHat;
import net.xtrafrancyz.mods.minidot.items.head.PerryPlatypus;
import net.xtrafrancyz.mods.minidot.items.head.Pipe;
import net.xtrafrancyz.mods.minidot.items.head.PlungerHat;
import net.xtrafrancyz.mods.minidot.items.head.PrincessCrown;
import net.xtrafrancyz.mods.minidot.items.head.ProssessedHat;
import net.xtrafrancyz.mods.minidot.items.head.PugHat;
import net.xtrafrancyz.mods.minidot.items.head.RainbowDrool;
import net.xtrafrancyz.mods.minidot.items.head.RamboBand;
import net.xtrafrancyz.mods.minidot.items.head.ReindeerHat;
import net.xtrafrancyz.mods.minidot.items.head.RespiratorHat;
import net.xtrafrancyz.mods.minidot.items.head.RoosterHat;
import net.xtrafrancyz.mods.minidot.items.head.SailorHat;
import net.xtrafrancyz.mods.minidot.items.head.SantaHat;
import net.xtrafrancyz.mods.minidot.items.head.Scarf2;
import net.xtrafrancyz.mods.minidot.items.head.ScaryHat;
import net.xtrafrancyz.mods.minidot.items.head.ScoutHat;
import net.xtrafrancyz.mods.minidot.items.head.ShrekEars;
import net.xtrafrancyz.mods.minidot.items.head.SlimeHat;
import net.xtrafrancyz.mods.minidot.items.head.SmallDiadem;
import net.xtrafrancyz.mods.minidot.items.head.SnowFlakeHat;
import net.xtrafrancyz.mods.minidot.items.head.SnowGlasses;
import net.xtrafrancyz.mods.minidot.items.head.SombreroHat;
import net.xtrafrancyz.mods.minidot.items.head.SouthParkHat;
import net.xtrafrancyz.mods.minidot.items.head.SpiderCrown;
import net.xtrafrancyz.mods.minidot.items.head.SpringHat;
import net.xtrafrancyz.mods.minidot.items.head.SpringWreathHat;
import net.xtrafrancyz.mods.minidot.items.head.SteampunkHat;
import net.xtrafrancyz.mods.minidot.items.head.SteepGlasses;
import net.xtrafrancyz.mods.minidot.items.head.StolasHat;
import net.xtrafrancyz.mods.minidot.items.head.StrawHat;
import net.xtrafrancyz.mods.minidot.items.head.SunglassesBlue;
import net.xtrafrancyz.mods.minidot.items.head.SunglassesHeart;
import net.xtrafrancyz.mods.minidot.items.head.SunglassesRound;
import net.xtrafrancyz.mods.minidot.items.head.SwineAct;
import net.xtrafrancyz.mods.minidot.items.head.THSCCharlesHeadphones;
import net.xtrafrancyz.mods.minidot.items.head.TelevisionHat;
import net.xtrafrancyz.mods.minidot.items.head.TracerGlasses;
import net.xtrafrancyz.mods.minidot.items.head.TrapHat;
import net.xtrafrancyz.mods.minidot.items.head.TurtleHat;
import net.xtrafrancyz.mods.minidot.items.head.TurtleShell;
import net.xtrafrancyz.mods.minidot.items.head.UnderwaterHat;
import net.xtrafrancyz.mods.minidot.items.head.UshankaHat;
import net.xtrafrancyz.mods.minidot.items.head.VikingHat;
import net.xtrafrancyz.mods.minidot.items.head.WitchHat;
import net.xtrafrancyz.mods.minidot.items.head.Wreath;
import net.xtrafrancyz.mods.minidot.items.head.YinYang;
import net.xtrafrancyz.mods.minidot.items.mask.AdrienMask;
import net.xtrafrancyz.mods.minidot.items.mask.GeometryDashDemonMask;
import net.xtrafrancyz.mods.minidot.items.mask.GeometryDashEasyMask;
import net.xtrafrancyz.mods.minidot.items.mask.GeometryDashHardMask;
import net.xtrafrancyz.mods.minidot.items.mask.GeometryDashHarderMask;
import net.xtrafrancyz.mods.minidot.items.mask.GeometryDashInsaneMask;
import net.xtrafrancyz.mods.minidot.items.mask.GeometryDashNormalMask;
import net.xtrafrancyz.mods.minidot.items.mask.HangryMask;
import net.xtrafrancyz.mods.minidot.items.mask.LuckyMask;
import net.xtrafrancyz.mods.minidot.items.mask.MarinetteMask;
import net.xtrafrancyz.mods.minidot.items.mask.MaskAnubis;
import net.xtrafrancyz.mods.minidot.items.mask.MaskBender;
import net.xtrafrancyz.mods.minidot.items.mask.MaskChick;
import net.xtrafrancyz.mods.minidot.items.mask.MaskCookies;
import net.xtrafrancyz.mods.minidot.items.mask.MaskCuteCactus;
import net.xtrafrancyz.mods.minidot.items.mask.MaskDino;
import net.xtrafrancyz.mods.minidot.items.mask.MaskDoggy;
import net.xtrafrancyz.mods.minidot.items.mask.MaskEagleBeak;
import net.xtrafrancyz.mods.minidot.items.mask.MaskEye;
import net.xtrafrancyz.mods.minidot.items.mask.MaskFurnace;
import net.xtrafrancyz.mods.minidot.items.mask.MaskGuards;
import net.xtrafrancyz.mods.minidot.items.mask.MaskHannya;
import net.xtrafrancyz.mods.minidot.items.mask.MaskMedical;
import net.xtrafrancyz.mods.minidot.items.mask.MaskMouth;
import net.xtrafrancyz.mods.minidot.items.mask.MaskPenguin;
import net.xtrafrancyz.mods.minidot.items.mask.MaskPinocchio;
import net.xtrafrancyz.mods.minidot.items.mask.MaskRabbit;
import net.xtrafrancyz.mods.minidot.items.mask.MaskRobot;
import net.xtrafrancyz.mods.minidot.items.mask.MaskSnowman;
import net.xtrafrancyz.mods.minidot.items.mask.MaskStranger;
import net.xtrafrancyz.mods.minidot.items.mask.MaskTiki;
import net.xtrafrancyz.mods.minidot.items.mask.MaskUnturned;
import net.xtrafrancyz.mods.minidot.items.mask.MaskWeeping;
import net.xtrafrancyz.mods.minidot.items.mask.MaskZlatovlaska;
import net.xtrafrancyz.mods.minidot.items.mask.ModelMask;
import net.xtrafrancyz.mods.minidot.items.mask.SCP096Mask;
import net.xtrafrancyz.mods.minidot.items.mask.SCPSculptureMask;
import net.xtrafrancyz.mods.minidot.items.mask.ShooterMask;
import net.xtrafrancyz.mods.minidot.items.mask.StopSignMask;
import net.xtrafrancyz.mods.minidot.items.pet.AndroidPet;
import net.xtrafrancyz.mods.minidot.items.pet.AngelDemon;
import net.xtrafrancyz.mods.minidot.items.pet.AnglerFish;
import net.xtrafrancyz.mods.minidot.items.pet.AppaPet;
import net.xtrafrancyz.mods.minidot.items.pet.AppleMonster;
import net.xtrafrancyz.mods.minidot.items.pet.ArcadeMachine;
import net.xtrafrancyz.mods.minidot.items.pet.AtomPet;
import net.xtrafrancyz.mods.minidot.items.pet.AxolotlBucket;
import net.xtrafrancyz.mods.minidot.items.pet.AxolotlPet;
import net.xtrafrancyz.mods.minidot.items.pet.BabyYodaPet;
import net.xtrafrancyz.mods.minidot.items.pet.BagItPet;
import net.xtrafrancyz.mods.minidot.items.pet.BearPet;
import net.xtrafrancyz.mods.minidot.items.pet.BedWars2017;
import net.xtrafrancyz.mods.minidot.items.pet.BedWars2018;
import net.xtrafrancyz.mods.minidot.items.pet.BedWars2020;
import net.xtrafrancyz.mods.minidot.items.pet.BedWars2021Bronze;
import net.xtrafrancyz.mods.minidot.items.pet.BedWars2021Default;
import net.xtrafrancyz.mods.minidot.items.pet.BedWars2021Gold;
import net.xtrafrancyz.mods.minidot.items.pet.BedWars2021Organizer;
import net.xtrafrancyz.mods.minidot.items.pet.BedWars2021Silver;
import net.xtrafrancyz.mods.minidot.items.pet.BedWars2021Stone;
import net.xtrafrancyz.mods.minidot.items.pet.BedWars2022Bronze;
import net.xtrafrancyz.mods.minidot.items.pet.BedWars2022Diamond;
import net.xtrafrancyz.mods.minidot.items.pet.BedWars2022Gold;
import net.xtrafrancyz.mods.minidot.items.pet.BedWars2022Silver;
import net.xtrafrancyz.mods.minidot.items.pet.BedWars2022Stone;
import net.xtrafrancyz.mods.minidot.items.pet.BedWars2022Wood;
import net.xtrafrancyz.mods.minidot.items.pet.BeeCatPet;
import net.xtrafrancyz.mods.minidot.items.pet.BeePet;
import net.xtrafrancyz.mods.minidot.items.pet.BillPet;
import net.xtrafrancyz.mods.minidot.items.pet.BimoPet;
import net.xtrafrancyz.mods.minidot.items.pet.BombPet;
import net.xtrafrancyz.mods.minidot.items.pet.BookGF1Pet;
import net.xtrafrancyz.mods.minidot.items.pet.BookGF2Pet;
import net.xtrafrancyz.mods.minidot.items.pet.BookGF3Pet;
import net.xtrafrancyz.mods.minidot.items.pet.BookStack;
import net.xtrafrancyz.mods.minidot.items.pet.BoscoPet;
import net.xtrafrancyz.mods.minidot.items.pet.BrainBasketPet;
import net.xtrafrancyz.mods.minidot.items.pet.BurgerPet;
import net.xtrafrancyz.mods.minidot.items.pet.ButterflyFlower;
import net.xtrafrancyz.mods.minidot.items.pet.CalamitasPet;
import net.xtrafrancyz.mods.minidot.items.pet.CatGun;
import net.xtrafrancyz.mods.minidot.items.pet.CatLegPet;
import net.xtrafrancyz.mods.minidot.items.pet.CeaslessVoid;
import net.xtrafrancyz.mods.minidot.items.pet.ChestPet;
import net.xtrafrancyz.mods.minidot.items.pet.ChickenBabyPet;
import net.xtrafrancyz.mods.minidot.items.pet.ChickenPet;
import net.xtrafrancyz.mods.minidot.items.pet.ChipmunkPet;
import net.xtrafrancyz.mods.minidot.items.pet.CloudPet;
import net.xtrafrancyz.mods.minidot.items.pet.ClownInBox;
import net.xtrafrancyz.mods.minidot.items.pet.ConsolePet;
import net.xtrafrancyz.mods.minidot.items.pet.CopperGolem;
import net.xtrafrancyz.mods.minidot.items.pet.CosmonautPet;
import net.xtrafrancyz.mods.minidot.items.pet.CreeperPet;
import net.xtrafrancyz.mods.minidot.items.pet.Cryogen;
import net.xtrafrancyz.mods.minidot.items.pet.CrystalMaiden;
import net.xtrafrancyz.mods.minidot.items.pet.CubeCompanion;
import net.xtrafrancyz.mods.minidot.items.pet.CupPet;
import net.xtrafrancyz.mods.minidot.items.pet.CupheadPet;
import net.xtrafrancyz.mods.minidot.items.pet.DeathNote;
import net.xtrafrancyz.mods.minidot.items.pet.DeerPet;
import net.xtrafrancyz.mods.minidot.items.pet.DragonCatPet;
import net.xtrafrancyz.mods.minidot.items.pet.DragonPet;
import net.xtrafrancyz.mods.minidot.items.pet.DuckyPet;
import net.xtrafrancyz.mods.minidot.items.pet.EasterBunny;
import net.xtrafrancyz.mods.minidot.items.pet.EasterCake;
import net.xtrafrancyz.mods.minidot.items.pet.EasterChicken;
import net.xtrafrancyz.mods.minidot.items.pet.EasterEgg;
import net.xtrafrancyz.mods.minidot.items.pet.ElfPet;
import net.xtrafrancyz.mods.minidot.items.pet.EndermanPet;
import net.xtrafrancyz.mods.minidot.items.pet.FallGuy;
import net.xtrafrancyz.mods.minidot.items.pet.FanPet;
import net.xtrafrancyz.mods.minidot.items.pet.FatNuggets;
import net.xtrafrancyz.mods.minidot.items.pet.FirstRang;
import net.xtrafrancyz.mods.minidot.items.pet.FlowerPet;
import net.xtrafrancyz.mods.minidot.items.pet.FoxPet;
import net.xtrafrancyz.mods.minidot.items.pet.FrogPet;
import net.xtrafrancyz.mods.minidot.items.pet.GhastPet;
import net.xtrafrancyz.mods.minidot.items.pet.GhostFoxPet;
import net.xtrafrancyz.mods.minidot.items.pet.GiftBig;
import net.xtrafrancyz.mods.minidot.items.pet.GiftPet;
import net.xtrafrancyz.mods.minidot.items.pet.GrandFatherFrost;
import net.xtrafrancyz.mods.minidot.items.pet.GrinchPet;
import net.xtrafrancyz.mods.minidot.items.pet.GrisSkelly;
import net.xtrafrancyz.mods.minidot.items.pet.HoglinPet;
import net.xtrafrancyz.mods.minidot.items.pet.HollowKnight;
import net.xtrafrancyz.mods.minidot.items.pet.HornetPet;
import net.xtrafrancyz.mods.minidot.items.pet.HotDog;
import net.xtrafrancyz.mods.minidot.items.pet.HuggyWuggy;
import net.xtrafrancyz.mods.minidot.items.pet.IceBlockPet;
import net.xtrafrancyz.mods.minidot.items.pet.IceCreamGlassPet;
import net.xtrafrancyz.mods.minidot.items.pet.Iceologer;
import net.xtrafrancyz.mods.minidot.items.pet.InfectedPet;
import net.xtrafrancyz.mods.minidot.items.pet.JPlushie;
import net.xtrafrancyz.mods.minidot.items.pet.JackTheGhost;
import net.xtrafrancyz.mods.minidot.items.pet.JoJoReference;
import net.xtrafrancyz.mods.minidot.items.pet.JudgmentTurtlePet;
import net.xtrafrancyz.mods.minidot.items.pet.KittenFishingPet;
import net.xtrafrancyz.mods.minidot.items.pet.KleeBomb;
import net.xtrafrancyz.mods.minidot.items.pet.KnucklesPet;
import net.xtrafrancyz.mods.minidot.items.pet.KodamaPet;
import net.xtrafrancyz.mods.minidot.items.pet.LanternPet;
import net.xtrafrancyz.mods.minidot.items.pet.Mandarin;
import net.xtrafrancyz.mods.minidot.items.pet.MarioMushroom;
import net.xtrafrancyz.mods.minidot.items.pet.MaskAkuAkuPet;
import net.xtrafrancyz.mods.minidot.items.pet.MegaBox;
import net.xtrafrancyz.mods.minidot.items.pet.Microphone;
import net.xtrafrancyz.mods.minidot.items.pet.MugmanPet;
import net.xtrafrancyz.mods.minidot.items.pet.MushroomPet;
import net.xtrafrancyz.mods.minidot.items.pet.MusicBox;
import net.xtrafrancyz.mods.minidot.items.pet.MysteryBlock;
import net.xtrafrancyz.mods.minidot.items.pet.NPlushie;
import net.xtrafrancyz.mods.minidot.items.pet.NootNootPet;
import net.xtrafrancyz.mods.minidot.items.pet.OliviaPet;
import net.xtrafrancyz.mods.minidot.items.pet.Oreo;
import net.xtrafrancyz.mods.minidot.items.pet.OwlPet;
import net.xtrafrancyz.mods.minidot.items.pet.PancakesPlate;
import net.xtrafrancyz.mods.minidot.items.pet.PandaPet;
import net.xtrafrancyz.mods.minidot.items.pet.Panteon;
import net.xtrafrancyz.mods.minidot.items.pet.PenguinPet;
import net.xtrafrancyz.mods.minidot.items.pet.Persona5Years;
import net.xtrafrancyz.mods.minidot.items.pet.PersonaClown;
import net.xtrafrancyz.mods.minidot.items.pet.PersonaCup;
import net.xtrafrancyz.mods.minidot.items.pet.PersonaCupid;
import net.xtrafrancyz.mods.minidot.items.pet.PersonaGrandArcades;
import net.xtrafrancyz.mods.minidot.items.pet.PersonaPet;
import net.xtrafrancyz.mods.minidot.items.pet.PersonaTank;
import net.xtrafrancyz.mods.minidot.items.pet.PhasmophobiaNotebook;
import net.xtrafrancyz.mods.minidot.items.pet.PinataPet;
import net.xtrafrancyz.mods.minidot.items.pet.PipePet;
import net.xtrafrancyz.mods.minidot.items.pet.PiratePet;
import net.xtrafrancyz.mods.minidot.items.pet.PlagueBringerPet;
import net.xtrafrancyz.mods.minidot.items.pet.PlayerPet;
import net.xtrafrancyz.mods.minidot.items.pet.PokeballPet;
import net.xtrafrancyz.mods.minidot.items.pet.PopItPet;
import net.xtrafrancyz.mods.minidot.items.pet.PredatorPet;
import net.xtrafrancyz.mods.minidot.items.pet.PrisonPickaxe2019;
import net.xtrafrancyz.mods.minidot.items.pet.ProbiusPet;
import net.xtrafrancyz.mods.minidot.items.pet.ProvidencePet;
import net.xtrafrancyz.mods.minidot.items.pet.PufferFishPet;
import net.xtrafrancyz.mods.minidot.items.pet.PumpkinPet;
import net.xtrafrancyz.mods.minidot.items.pet.PuppyBoxPet;
import net.xtrafrancyz.mods.minidot.items.pet.RaccoonPet;
import net.xtrafrancyz.mods.minidot.items.pet.RamenPet;
import net.xtrafrancyz.mods.minidot.items.pet.ReaperPet;
import net.xtrafrancyz.mods.minidot.items.pet.RoyalAnvil;
import net.xtrafrancyz.mods.minidot.items.pet.SCP049;
import net.xtrafrancyz.mods.minidot.items.pet.SCP500;
import net.xtrafrancyz.mods.minidot.items.pet.SandGlass;
import net.xtrafrancyz.mods.minidot.items.pet.SharkCatPet;
import net.xtrafrancyz.mods.minidot.items.pet.ShavermaPet;
import net.xtrafrancyz.mods.minidot.items.pet.SheepPig;
import net.xtrafrancyz.mods.minidot.items.pet.SignusPet;
import net.xtrafrancyz.mods.minidot.items.pet.SkeletonDragon;
import net.xtrafrancyz.mods.minidot.items.pet.SkeletonPet;
import net.xtrafrancyz.mods.minidot.items.pet.SkullPet;
import net.xtrafrancyz.mods.minidot.items.pet.SledPet;
import net.xtrafrancyz.mods.minidot.items.pet.SlimePet;
import net.xtrafrancyz.mods.minidot.items.pet.SmileyJess;
import net.xtrafrancyz.mods.minidot.items.pet.SnailPet;
import net.xtrafrancyz.mods.minidot.items.pet.SnowMaiden;
import net.xtrafrancyz.mods.minidot.items.pet.SnowManPet;
import net.xtrafrancyz.mods.minidot.items.pet.Spinner;
import net.xtrafrancyz.mods.minidot.items.pet.SpinnerFlash;
import net.xtrafrancyz.mods.minidot.items.pet.SpringKeeper;
import net.xtrafrancyz.mods.minidot.items.pet.SprucePet;
import net.xtrafrancyz.mods.minidot.items.pet.SummerBallPet;
import net.xtrafrancyz.mods.minidot.items.pet.TardisPet;
import net.xtrafrancyz.mods.minidot.items.pet.TeaCup;
import net.xtrafrancyz.mods.minidot.items.pet.ToyStoryAlienPet;
import net.xtrafrancyz.mods.minidot.items.pet.TractorPet;
import net.xtrafrancyz.mods.minidot.items.pet.TriggerTeddy;
import net.xtrafrancyz.mods.minidot.items.pet.TrumpetPet;
import net.xtrafrancyz.mods.minidot.items.pet.UnluckyCatPet;
import net.xtrafrancyz.mods.minidot.items.pet.VPlushie;
import net.xtrafrancyz.mods.minidot.items.pet.VivillonPet;
import net.xtrafrancyz.mods.minidot.items.pet.WallE;
import net.xtrafrancyz.mods.minidot.items.pet.WalrusPet;
import net.xtrafrancyz.mods.minidot.items.pet.WardenPet;
import net.xtrafrancyz.mods.minidot.items.pet.WildDuckPet;
import net.xtrafrancyz.mods.minidot.items.pet.WitchPet;
import net.xtrafrancyz.mods.minidot.items.pet.WumpusPet;
import net.xtrafrancyz.mods.minidot.items.pet.XmasGiftPet;
import net.xtrafrancyz.mods.minidot.items.pet.YTButton;
import net.xtrafrancyz.mods.minidot.items.pet.ZombiePet;

public class ItemRegistry
{
    public static final Map<Integer, BaseItem> ITEMS = new LinkedHashMap();

    private static void init()
    {
        register(10132, (new ScaryHat()).setCollection(ItemCollection.HALLOWEEN));
        register(10131, (new BatHat()).setCollection(ItemCollection.HALLOWEEN));
        register(10126, (new FaceHugger()).setCollection(ItemCollection.HALLOWEEN));
        register(10110, (new CyborgHat()).setCollection(ItemCollection.HALLOWEEN));
        register(37, (new ShrekEars()).setCollection(ItemCollection.HALLOWEEN));
        register(10137, (new AsianHat()).setCollection(ItemCollection.FALL));
        register(10136, (new SpiderCrown()).setCollection(ItemCollection.FALL));
        register(10135, (new StolasHat()).setCollection(ItemCollection.FALL));
        register(10134, (new Muzzle()).setCollection(ItemCollection.FALL));
        register(10133, (new HornsHead()).setCollection(ItemCollection.FALL));
        register(10160, (new HairPinFlowers("blue")).setCollection(ItemCollection.SUMMER).setNew(true));
        register(10159, (new HairPinFlowers("pink")).setCollection(ItemCollection.SUMMER).setNew(true));
        register(10158, (new ButterflyHat("white")).setCollection(ItemCollection.SUMMER).setNew(true));
        register(10157, (new ButterflyHat("red")).setCollection(ItemCollection.SUMMER).setNew(true));
        register(10156, (new ButterflyHat("purple")).setCollection(ItemCollection.SUMMER).setNew(true));
        register(10155, (new ButterflyHat("black")).setCollection(ItemCollection.SUMMER).setNew(true));
        register(10154, (new ButterflyHat("aqua")).setCollection(ItemCollection.SUMMER).setNew(true));
        register(10130, (new SunglassesRound()).setCollection(ItemCollection.SUMMER));
        register(10129, (new SunglassesHeart()).setCollection(ItemCollection.SUMMER));
        register(10128, (new SunglassesBlue()).setCollection(ItemCollection.SUMMER));
        register(10125, (new SpringWreathHat()).setCollection(ItemCollection.SUMMER));
        register(10109, (new CrabCrown()).setCollection(ItemCollection.SUMMER));
        register(10123, (new StrawHat()).setCollection(ItemCollection.SUMMER));
        register(10108, (new BunnyPanama()).setCollection(ItemCollection.EASTER));
        register(10107, (new BunnyHelm()).setCollection(ItemCollection.EASTER));
        register(10150, (new SpringHat()).setCollection(ItemCollection.SPRING));
        register(10149, (new HairKnot("yellow")).setCollection(ItemCollection.SPRING));
        register(10148, (new HairKnot("green")).setCollection(ItemCollection.SPRING));
        register(10147, (new HairKnot("blue")).setCollection(ItemCollection.SPRING));
        register(10146, (new HairKnot("red")).setCollection(ItemCollection.SPRING));
        register(10145, (new PrincessCrown()).setCollection(ItemCollection.SPRING));
        register(10144, (new SmallDiadem()).setCollection(ItemCollection.SPRING));
        register(10143, (new TurtleShell()).setCollection(ItemCollection.SPRING));
        register(10112, (new HeadSprout()).setCollection(ItemCollection.SPRING));
        register(10124, (new SnowFlakeHat()).setCollection(ItemCollection.WINTER));
        register(10111, (new ElfHat()).setCollection(ItemCollection.WINTER));
        register(49, (new DeerHornsCurvedHat()).setCollection(ItemCollection.WINTER));
        register(48, (new SantaHat()).setCollection(ItemCollection.WINTER));
        register(41, (new ElfEars()).setCollection(ItemCollection.WINTER));
        register(27, (new ChristmasHat2()).setCollection(ItemCollection.WINTER));
        register(28, (new Scarf2("green")).setCollection(ItemCollection.WINTER));
        register(29, (new Scarf2("white")).setCollection(ItemCollection.WINTER));
        register(30, (new Scarf2("purple")).setCollection(ItemCollection.WINTER));
        register(31, (new Scarf2("red")).setCollection(ItemCollection.WINTER));
        register(1, (new ChristmasHat()).setCollection(ItemCollection.WINTER));
        register(2, (new DeerHornsHat()).setCollection(ItemCollection.WINTER));
        register(11, (new ChristmasNose()).setCollection(ItemCollection.WINTER));
        register(12, (new IceHat()).setCollection(ItemCollection.WINTER));
        register(10166, (new SailorHat()).setNew(true));
        register(10165, (new OniHat()).setNew(true));
        register(10164, (new HutaoHat()).setNew(true));
        register(10163, (new HeadStarsHat()).setNew(true));
        register(10162, (new GeneralRuffsCap()).setNew(true));
        register(10161, (new ChessBoard()).setNew(true));
        register(10153, new THSCCharlesHeadphones());
        register(10151, new AntmanHelm());
        register(10142, new LokiHelmet());
        register(10141, new MarvelScarletTiara());
        register(10140, new FallenAngelNimbus());
        register(10139, new TrapHat());
        register(10138, new FrogHelm());
        register(10127, new AdrienMask());
        register(10122, new BobFettaHelm());
        register(10121, new DjangoFettaHelm());
        register(10120, new MandalorianHelm());
        register(10119, new SwineAct());
        register(10118, new SteampunkHat());
        register(10117, new ReindeerHat());
        register(10116, new NinjaHeadband("black"));
        register(10115, new NinjaHeadband("red"));
        register(10114, new HypnoGlasses());
        register(10113, new HolographicIroquois());
        register(10106, new HelmetSamurai());
        register(10105, new HelmetTank());
        register(10104, new TelevisionHat());
        register(10103, new MagicianHat());
        register(10102, new HatterHat());
        register(10101, new NvgHat());
        register(10100, new UnderwaterHat());
        register(10099, new BeaverHat());
        register(10098, new HelmetPubg());
        register(10097, new BuilderHat());
        register(10096, new HelmetCovid19());
        register(10095, new ClownHat());
        register(10094, new Wreath("green"));
        register(10093, new Wreath("gold"));
        register(10092, new Wreath("ice"));
        register(10091, new HelmetFlash());
        register(10090, new FireGlasses());
        register(10089, new GlassHat("rainbow"));
        register(10088, new GlassHat("normal"));
        register(10087, new HelmetEagle());
        register(10086, new PugHat());
        register(10085, new HelmetMouse("blue"));
        register(10084, new HelmetMouse("pink"));
        register(10083, new HelmetMouse("orange"));
        register(10082, new HelmetVillager());
        register(10081, new HelmetZombie());
        register(10080, new LaserHat());
        register(10079, new Nimbus());
        register(10078, new PerryPlatypus());
        register(10006, new PenguinHat());
        register(10077, new HornsHat());
        register(10076, new ChickenHat());
        register(10075, new BearHat("grizzly"));
        register(10074, new BearHat("white"));
        register(10073, new BearHat("panda"));
        register(10072, new RamboBand());
        register(10071, new Monocle());
        register(10070, new FezHat());
        register(10069, new BunnyHat());
        register(10068, new PlungerHat());
        register(10067, new PanamaHat());
        register(10066, new ScoutHat());
        register(10065, new HeartHat("rainbow"));
        register(10064, new HeartHat("rainbow2"));
        register(10063, new BoneEarsHat("white"));
        register(10062, new BoneEarsHat("black"));
        register(10061, new BoneEarsHat("purple"));
        register(10060, new BoneEarsHat("pink"));
        register(10059, new BoneEarsHat("biege"));
        register(10058, new DogEarsHat("orange"));
        register(10057, new DogEarsHat("gray"));
        register(10056, new DogEarsHat("red"));
        register(10055, new DogEarsHat("green"));
        register(10054, new DogEarsHat("purple"));
        register(10053, new DogEarsHat("brown"));
        register(10052, new DogEarsHat("white"));
        register(10051, new SteepGlasses());
        register(10050, new DollarGlasses());
        register(10049, new YinYang());
        register(10048, new Peepers());
        register(10047, new Pipe());
        register(10046, new Mustache());
        register(10045, new Glasses());
        register(10044, new MoustacheGlasses());
        register(10043, new Diadem());
        register(10001, new Headphones());
        register(10002, new HeartHat("basic"));
        register(10003, new UshankaHat());
        register(10004, new CreeperHat());
        register(10005, new AnvilHat());
        register(10007, new HamsterHat());
        register(10008, new MarioHat("mario"));
        register(10009, new MarioHat("luigi"));
        register(10010, new Hood("white"));
        register(10011, new Hood("black"));
        register(10012, new SlimeHat());
        register(10013, new PandaHat());
        register(10014, new IndianaJonesHat());
        register(10015, new TurtleHat());
        register(10016, new RespiratorHat());
        register(10017, new VikingHat());
        register(10018, new SnowGlasses());
        register(10019, new ArrowHat());
        register(10020, new FlowersHat());
        register(10021, new HelicopterHat());
        register(10022, new SombreroHat());
        register(10023, new FoxEarsHat("black"));
        register(10024, new FoxEarsHat("yellow"));
        register(10025, new FoxEarsHat("orange"));
        register(10026, new KiwiHat());
        register(10027, new CoffeeHat());
        register(10028, new ProssessedHat());
        register(10029, new BrainSlug());
        register(10030, new CakeHat());
        register(10031, new MinerHat());
        register(10032, new CrownIceKingHat());
        register(10033, new BearsEarsHat());
        register(10034, new SouthParkHat("kartman"));
        register(10035, new SouthParkHat("sten"));
        register(10036, new DealWithItHat());
        register(10037, new ElectricHornsHat());
        register(10038, new RainbowDrool());
        register(10039, new WitchHat());
        register(10040, new MayaHat());
        register(10041, new RoosterHat());
        register(10042, new DevilHorns());
        register(20210, (new LuckyMask()).setCollection(ItemCollection.HALLOWEEN));
        register(20209, (new HangryMask()).setCollection(ItemCollection.HALLOWEEN));
        register(32, (new MaskSnowman()).setCollection(ItemCollection.WINTER));
        register(20211, (new ShooterMask()).setNew(true));
        register(20208, new GeometryDashDemonMask());
        register(20207, new GeometryDashInsaneMask());
        register(20206, new GeometryDashHarderMask());
        register(20205, new GeometryDashHardMask());
        register(20204, new GeometryDashNormalMask());
        register(20203, new GeometryDashEasyMask());
        register(20202, new StopSignMask());
        register(20201, new SCPSculptureMask());
        register(20200, new SCP096Mask());
        register(20199, new MarinetteMask());
        register(20198, new MaskAnubis());
        register(20197, new MaskRobot());
        register(20196, new MaskEye());
        register(20195, new TracerGlasses("black"));
        register(20194, new TracerGlasses("gray"));
        register(20193, new MaskRabbit());
        register(20192, new MaskMedical());
        register(20191, new ModelMask("svtfoe_star"));
        register(20190, new ModelMask("svtfoe_eclipsa"));
        register(20189, new ModelMask("svtfoe_heckapoo"));
        register(20188, new ModelMask("svtfoe_moon"));
        register(20187, new ModelMask("svtfoe_talon"));
        register(20186, new ModelMask("svtfoe_mewberty"));
        register(20185, new ModelMask("svtfoe_toffee"));
        register(20184, new ModelMask("svtfoe_glossaryck"));
        register(20183, new ModelMask("svtfoe_globgor"));
        register(20182, new ModelMask("svtfoe_meteora"));
        register(20181, new ModelMask("svtfoe_rhombulus"));
        register(20180, new ModelMask("svtfoe_jenna"));
        register(20179, new ModelMask("svtfoe_solaria"));
        register(20178, new MaskHannya());
        register(20148, new ModelMask("hall_frankenstein"));
        register(20149, new ModelMask("hall_werewolf"));
        register(20150, new ModelMask("hall_vampire"));
        register(20151, new ModelMask("hall_wraith"));
        register(20152, new ModelMask("hall_negasteve"));
        register(20153, new ModelMask("hall_pennywise"));
        register(20154, new ModelMask("hall_pumpkin"));
        register(20155, new ModelMask("hall_sans"));
        register(20156, new ModelMask("hall_skull"));
        register(20157, new ModelMask("hall_steve"));
        register(20177, new MaskTiki());
        register(20176, new MaskWeeping());
        register(20175, new MaskZlatovlaska());
        register(20174, new MaskGuards());
        register(20173, new MaskCuteCactus());
        register(20172, new MaskPinocchio());
        register(20171, new MaskDoggy());
        register(20169, new MaskDino("blue"));
        register(20168, new MaskDino("green"));
        register(20167, new MaskDino("pink"));
        register(20166, new MaskDino("purple"));
        register(20165, new MaskDino("red"));
        register(20164, new MaskMouth());
        register(20163, new MaskChick());
        register(20158, new MaskBender());
        register(20159, new MaskStranger());
        register(20160, new MaskEagleBeak());
        register(20161, new MaskCookies());
        register(20162, new MaskFurnace());
        register(20147, new MaskPenguin());
        register(20001, new ModelMask("mrv_deadpool"));
        register(20002, new ModelMask("cavespider"));
        register(20003, new ModelMask("creeper"));
        register(20004, new ModelMask("pigman"));
        register(20005, new ModelMask("skeleton"));
        register(20006, new ModelMask("witherskeleton"));
        register(20007, new ModelMask("wither"));
        register(20008, new ModelMask("zombi"));
        register(20009, new ModelMask("heroender"));
        register(20010, new ModelMask("slime"));
        register(20011, new ModelMask("spider"));
        register(20012, new ModelMask("magma"));
        register(20013, new ModelMask("pig"));
        register(20014, new ModelMask("ocelot"));
        register(20015, new ModelMask("blaze"));
        register(20016, new ModelMask("cow"));
        register(20017, new ModelMask("enderman"));
        register(20018, new ModelMask("herobrine"));
        register(20019, new ModelMask("mushroom"));
        register(20020, new ModelMask("steve"));
        register(20021, new ModelMask("black_steve"));
        register(20022, new ModelMask("beast_boy"));
        register(20023, new ModelMask("anonymous"));
        register(20024, new ModelMask("at_finn"));
        register(20025, new ModelMask("at_jake"));
        register(20026, new ModelMask("dc_joker"));
        register(20027, new ModelMask("dc_batman"));
        register(20028, new ModelMask("dc_bane"));
        register(20029, new ModelMask("patrick"));
        register(20030, new ModelMask("pikachu"));
        register(20031, new ModelMask("mrv_ironman"));
        register(20032, new ModelMask("mrv_nick_fury"));
        register(20033, new ModelMask("mrv_captain_america"));
        register(20034, new ModelMask("mrv_groot"));
        register(20035, new ModelMask("payday_dallas"));
        register(20036, new ModelMask("payday_hoxton"));
        register(20037, new ModelMask("payday_wolf"));
        register(20038, new ModelMask("payday_chains"));
        register(20039, new ModelMask("saw"));
        register(20040, new ModelMask("jason_v"));
        register(20041, new ModelMask("d2_jugger"));
        register(20042, new ModelMask("d2_void"));
        register(20043, new ModelMask("d2_axe"));
        register(20044, new ModelMask("d2_rubik"));
        register(20045, new ModelMask("d2_bh"));
        register(20046, new ModelMask("d2_invoker"));
        register(20047, new ModelMask("d2_tidehunter"));
        register(20048, new ModelMask("d2_drowranger"));
        register(20049, new ModelMask("d2_riki"));
        register(20050, new ModelMask("d2_sk"));
        register(20051, new ModelMask("d2_lycan"));
        register(20052, new ModelMask("d2_antimage"));
        register(20053, new ModelMask("d2_kunkka"));
        register(20054, new ModelMask("d2_templar"));
        register(20055, new ModelMask("d2_pudge"));
        register(20056, new ModelMask("d2_lina"));
        register(20057, new ModelMask("d2_cm"));
        register(20058, new ModelMask("d2_slark"));
        register(20059, new ModelMask("d2_dk"));
        register(20060, new ModelMask("d2_fura"));
        register(20061, new ModelMask("d2_bs"));
        register(20062, new ModelMask("d2_abbadon"));
        register(20063, new ModelMask("d2_undying"));
        register(20064, new ModelMask("d2_pl"));
        register(20065, new ModelMask("d2_warlock"));
        register(20066, new ModelMask("tmnt_donatello"));
        register(20067, new ModelMask("tmnt_leonardo"));
        register(20068, new ModelMask("tmnt_michelangelo"));
        register(20069, new ModelMask("tmnt_raphael"));
        register(20070, new ModelMask("fnaf_freddy"));
        register(20072, new ModelMask("fnaf_chica"));
        register(20073, new ModelMask("fnaf_mangle"));
        register(20074, new ModelMask("fnaf_foxy"));
        register(20075, new ModelMask("fnaf_marionette"));
        register(20076, new ModelMask("fnaf_bonnie"));
        register(20077, new ModelMask("fnaf_springtrap"));
        register(20078, new ModelMask("fnaf_purple_guy"));
        register(20079, new ModelMask("fnaf_balloon_boy"));
        register(20080, new ModelMask("vass"));
        register(20081, new ModelMask("mcdonald"));
        register(20082, new ModelMask("facehrena"));
        register(20083, new MaskUnturned("untrn_1"));
        register(20084, new MaskUnturned("untrn_2"));
        register(20085, new MaskUnturned("untrn_3"));
        register(20086, new MaskUnturned("untrn_4"));
        register(20087, new MaskUnturned("untrn_5"));
        register(20088, new MaskUnturned("untrn_6"));
        register(20089, new MaskUnturned("untrn_7"));
        register(20090, new MaskUnturned("untrn_8"));
        register(20091, new MaskUnturned("untrn_9"));
        register(20092, new MaskUnturned("untrn_10"));
        register(20093, new MaskUnturned("untrn_11"));
        register(20094, new MaskUnturned("untrn_12"));
        register(20095, new MaskUnturned("untrn_13"));
        register(20096, new MaskUnturned("untrn_14"));
        register(20097, new MaskUnturned("untrn_15"));
        register(20098, new MaskUnturned("untrn_16"));
        register(20099, new MaskUnturned("untrn_17"));
        register(20100, new MaskUnturned("untrn_18"));
        register(20101, new MaskUnturned("untrn_19"));
        register(20102, new MaskUnturned("untrn_20"));
        register(20135, new MaskUnturned("untrn_21"));
        register(20136, new MaskUnturned("untrn_22"));
        register(20137, new MaskUnturned("untrn_23"));
        register(20138, new MaskUnturned("untrn_24"));
        register(20139, new MaskUnturned("untrn_25"));
        register(20140, new MaskUnturned("untrn_26"));
        register(20141, new MaskUnturned("untrn_27"));
        register(20142, new MaskUnturned("untrn_28"));
        register(20143, new MaskUnturned("untrn_29"));
        register(20144, new MaskUnturned("untrn_30"));
        register(20145, new MaskUnturned("untrn_31"));
        register(20146, new MaskUnturned("untrn_32"));
        register(20103, new ModelMask("cake"));
        register(20104, new ModelMask("pr_red"));
        register(20105, new ModelMask("pr_blue"));
        register(20106, new ModelMask("pr_yellow"));
        register(20107, new ModelMask("pr_green"));
        register(20108, new ModelMask("pr_pink"));
        register(20109, new ModelMask("pr_black"));
        register(20110, new ModelMask("pr_white"));
        register(20111, new ModelMask("hellboy"));
        register(20112, new ModelMask("kratos"));
        register(20113, new ModelMask("mummy"));
        register(20114, new ModelMask("mr_t"));
        register(20115, new ModelMask("skull"));
        register(20116, new ModelMask("trollface"));
        register(20117, new ModelMask("dirt"));
        register(20118, new ModelMask("doge"));
        register(20119, new ModelMask("sonic"));
        register(20120, new ModelMask("panda"));
        register(20121, new ModelMask("onepunch"));
        register(20122, new ModelMask("ninja"));
        register(20123, new ModelMask("sloth"));
        register(20124, new ModelMask("misha"));
        register(20125, new ModelMask("knight"));
        register(20126, new ModelMask("minion"));
        register(20127, new ModelMask("mlp_rainbow_dash"));
        register(20128, new ModelMask("mlp_fluttershy"));
        register(20129, new ModelMask("mlp_twilight_sparkle"));
        register(20130, new ModelMask("mlp_applejack"));
        register(20131, new ModelMask("mlp_rarity"));
        register(20132, new ModelMask("mlp_pinki_pie"));
        register(20133, new ModelMask("mlp_celestia"));
        register(20134, new ModelMask("mlp_luna"));
        register(30087, (new BloodyAxe()).setCollection(ItemCollection.HALLOWEEN));
        register(30086, (new Cauldron()).setCollection(ItemCollection.HALLOWEEN));
        register(30074, (new DraculasCloak()).setCollection(ItemCollection.HALLOWEEN));
        register(30073, (new Scythe()).setCollection(ItemCollection.HALLOWEEN));
        register(30057, (new IronChains()).setCollection(ItemCollection.HALLOWEEN));
        register(30106, (new ButterflyWings("green")).setCollection(ItemCollection.SUMMER).setNew(true));
        register(30105, (new ButterflyWings("blue")).setCollection(ItemCollection.SUMMER).setNew(true));
        register(30104, (new ButterflyWings("yellow")).setCollection(ItemCollection.SUMMER).setNew(true));
        register(30103, (new ButterflyWings("red")).setCollection(ItemCollection.SUMMER).setNew(true));
        register(30102, (new HikingBackpack()).setCollection(ItemCollection.SUMMER).setNew(true));
        register(30072, (new Lifebuoy()).setCollection(ItemCollection.SUMMER));
        register(30070, (new InflatableRingUnicorn("pink")).setCollection(ItemCollection.SUMMER));
        register(30069, (new InflatableRingUnicorn("white")).setCollection(ItemCollection.SUMMER));
        register(30068, (new BodyFlower("white")).setCollection(ItemCollection.SUMMER));
        register(30067, (new BodyFlower("red")).setCollection(ItemCollection.SUMMER));
        register(30066, (new BodyFlower("blue")).setCollection(ItemCollection.SUMMER));
        register(30065, (new BodyFlower("pink")).setCollection(ItemCollection.SUMMER));
        register(30064, (new BodyFlower("purple")).setCollection(ItemCollection.SUMMER));
        register(30093, (new Snowboard("technology")).setCollection(ItemCollection.WINTER).setNew(true));
        register(30092, (new Snowboard("rainbow")).setCollection(ItemCollection.WINTER).setNew(true));
        register(30091, (new Snowboard("vime")).setCollection(ItemCollection.WINTER).setNew(true));
        register(30090, (new Mittens()).setCollection(ItemCollection.WINTER).setNew(true));
        register(30089, (new CandyWings()).setCollection(ItemCollection.WINTER).setNew(true));
        register(30035, (new Garlands(Garlands.RGB)).setCollection(ItemCollection.WINTER));
        register(30036, (new Garlands(Garlands.CMYK)).setCollection(ItemCollection.WINTER));
        register(30113, (new DogBackpack("jack")).setNew(true));
        register(30112, (new DogBackpack("white")).setNew(true));
        register(30111, (new DogBackpack("brown")).setNew(true));
        register(30110, (new FireTubes()).setNew(true));
        register(30109, (new WhiteAngelWings()).setNew(true));
        register(30108, (new Trident()).setNew(true));
        register(30107, (new AncientHammer()).setNew(true));
        register(30101, new TargetBody());
        register(30100, new DroneWings());
        register(30099, new Tentacles("aqua"));
        register(30098, new Tentacles("purple"));
        register(30097, new Tentacles("orange"));
        register(30096, new Tentacles("red"));
        register(30095, new LuckyBowTie());
        register(30094, new Piglin());
        register(30088, new Katana());
        register(30085, new Peacock());
        register(30084, new MechanicalWings());
        register(30083, new FallenWings());
        register(30082, new KleeBackpack());
        register(30081, new HogwartsScarf("slytherin"));
        register(30080, new HogwartsScarf("ravenclaw"));
        register(30079, new HogwartsScarf("hufflepuff"));
        register(30078, new HogwartsScarf("gryffindor"));
        register(30071, new JetPack());
        register(30063, new BackPack("green"));
        register(30062, new BackPack("red"));
        register(30061, new BackPack("orange"));
        register(30060, new BackPack("black"));
        register(30059, new BackPack("blue"));
        register(30056, new PetBackpack("blue"));
        register(30055, new PetBackpack("pink"));
        register(30054, new PetBackpack("yellow"));
        register(30053, new PetBackpack("green"));
        register(30052, new PetBackpack("gray"));
        register(30058, new Quiver());
        register(30077, new LifeVest("green"));
        register(30076, new LifeVest("gray"));
        register(30075, new LifeVest("red"));
        register(30051, new LifeVest("yellow"));
        register(30049, new FieryWings("red"));
        register(30048, new FieryWings("blue"));
        register(30047, new FieryWings("green"));
        register(30046, new FieryWings("pink"));
        register(30045, new FieryWings("dark"));
        register(30044, new Scarf("red"));
        register(30043, new Scarf("white"));
        register(30042, new Scarf("green"));
        register(30041, new Scarf("blue"));
        register(30040, new Butterfly23("purple"));
        register(30039, new Butterfly23("black"));
        register(30038, new Butterfly23("white"));
        register(30037, new Butterfly23("red"));
        register(30001, new FirstWings("white"));
        register(30002, new FirstWings("black"));
        register(30003, new FirstWings("blue"));
        register(30004, new FirstWings("pink"));
        register(30005, new FirstWings("green"));
        register(30006, new FirstWings("rainbow"));
        register(30007, new DemonicWings());
        register(30008, new BigWings("black"));
        register(30009, new BigWings("white"));
        register(30010, new BigWings("orange"));
        register(30011, new BigWings("rainbow"));
        register(30012, new BatterflyWings());
        register(30013, new BatterflyWingsV2("white"));
        register(30014, new BatterflyWingsV2("orange"));
        register(30015, new BatterflyWingsV2("blue"));
        register(30016, new BatterflyWingsV2("green"));
        register(30017, new WingsDragon());
        register(30018, new NeonWings("blue"));
        register(30019, new NeonWings("red"));
        register(30020, new NeonWings("green"));
        register(30021, new NeonWings("purple"));
        register(30022, new NeonWings("yellow"));
        register(30023, new ExoWings("blue"));
        register(30024, new ExoWings("red"));
        register(30025, new ExoWings("green"));
        register(30026, new ExoWings("white"));
        register(30027, new ExoWings("yellow"));
        register(30050, new MercyWings("red"));
        register(30028, new MercyWings("yellow"));
        register(30029, new MercyWings("orange"));
        register(30030, new MercyWings("purple"));
        register(30031, new MercyWings("blue"));
        register(30032, new MercyWings("gold"));
        register(30033, new SkyeyWings());
        register(30034, new BatWings());
        register(104, (new PrisonPickaxe2019("rainbow")).setCollection(ItemCollection.GENERIC_RARE));
        register(103, (new PrisonPickaxe2019("sapphire")).setCollection(ItemCollection.GENERIC_RARE));
        register(102, (new PrisonPickaxe2019("ruby")).setCollection(ItemCollection.GENERIC_RARE));
        register(101, (new PrisonPickaxe2019("emerald")).setCollection(ItemCollection.GENERIC_RARE));
        register(87, (new PersonaGrandArcades()).setCollection(ItemCollection.GENERIC_RARE));
        register(69, (new PersonaClown()).setCollection(ItemCollection.GENERIC_RARE).setNew(true));
        register(62, (new PersonaTank()).setCollection(ItemCollection.GENERIC_RARE));
        register(55, (new PersonaCupid()).setCollection(ItemCollection.GENERIC_RARE));
        register(33, (new PrisonPickaxe2019("diamond")).setCollection(ItemCollection.GENERIC_RARE));
        register(34, (new PrisonPickaxe2019("iron")).setCollection(ItemCollection.GENERIC_RARE));
        register(35, (new PrisonPickaxe2019("stone")).setCollection(ItemCollection.GENERIC_RARE));
        register(36, (new PrisonPickaxe2019("wood")).setCollection(ItemCollection.GENERIC_RARE));
        register(8, (new Persona5Years()).setCollection(ItemCollection.GENERIC_RARE));
        register(125, (new BedWars2022Diamond()).setCollection(ItemCollection.TOURNAMENT).setNew(true));
        register(124, (new BedWars2022Gold()).setCollection(ItemCollection.TOURNAMENT).setNew(true));
        register(123, (new BedWars2022Silver()).setCollection(ItemCollection.TOURNAMENT).setNew(true));
        register(122, (new BedWars2022Bronze()).setCollection(ItemCollection.TOURNAMENT).setNew(true));
        register(121, (new BedWars2022Stone()).setCollection(ItemCollection.TOURNAMENT).setNew(true));
        register(120, (new BedWars2022Wood()).setCollection(ItemCollection.TOURNAMENT).setNew(true));
        register(68, (new BedWars2021Stone()).setCollection(ItemCollection.TOURNAMENT));
        register(67, (new BedWars2021Silver()).setCollection(ItemCollection.TOURNAMENT));
        register(66, (new BedWars2021Organizer()).setCollection(ItemCollection.TOURNAMENT));
        register(65, (new BedWars2021Gold()).setCollection(ItemCollection.TOURNAMENT));
        register(64, (new BedWars2021Default()).setCollection(ItemCollection.TOURNAMENT));
        register(63, (new BedWars2021Bronze()).setCollection(ItemCollection.TOURNAMENT));
        register(61, (new Panteon("classic")).setCollection(ItemCollection.TOURNAMENT));
        register(60, (new Panteon("grid")).setCollection(ItemCollection.TOURNAMENT));
        register(59, (new Panteon("bronze")).setCollection(ItemCollection.TOURNAMENT));
        register(58, (new Panteon("silver")).setCollection(ItemCollection.TOURNAMENT));
        register(57, (new Panteon("gold")).setCollection(ItemCollection.TOURNAMENT));
        register(56, (new Panteon("org")).setCollection(ItemCollection.TOURNAMENT));
        register(47, (new BedWars2020("classic")).setCollection(ItemCollection.TOURNAMENT));
        register(46, (new BedWars2020("stone")).setCollection(ItemCollection.TOURNAMENT));
        register(45, (new BedWars2020("bronze")).setCollection(ItemCollection.TOURNAMENT));
        register(44, (new BedWars2020("silver")).setCollection(ItemCollection.TOURNAMENT));
        register(43, (new BedWars2020("gold")).setCollection(ItemCollection.TOURNAMENT));
        register(42, (new BedWars2020("ice")).setCollection(ItemCollection.TOURNAMENT));
        register(3, (new BedWars2017("classic")).setCollection(ItemCollection.TOURNAMENT));
        register(4, (new BedWars2017("bronze")).setCollection(ItemCollection.TOURNAMENT));
        register(5, (new BedWars2017("silver")).setCollection(ItemCollection.TOURNAMENT));
        register(6, (new BedWars2017("gold")).setCollection(ItemCollection.TOURNAMENT));
        register(7, (new PersonaCup()).setCollection(ItemCollection.TOURNAMENT));
        register(14, (new BedWars2018("member")).setCollection(ItemCollection.TOURNAMENT));
        register(15, (new BedWars2018("warrior")).setCollection(ItemCollection.TOURNAMENT));
        register(16, (new BedWars2018("bronze")).setCollection(ItemCollection.TOURNAMENT));
        register(17, (new BedWars2018("silver")).setCollection(ItemCollection.TOURNAMENT));
        register(18, (new BedWars2018("gold")).setCollection(ItemCollection.TOURNAMENT));
        register(100, (new CalamitasPet()).setCollection(ItemCollection.HALLOWEEN));
        register(99, (new AppleMonster()).setCollection(ItemCollection.HALLOWEEN));
        register(98, (new TriggerTeddy()).setCollection(ItemCollection.HALLOWEEN));
        register(97, (new AngelDemon()).setCollection(ItemCollection.HALLOWEEN));
        register(96, (new SmileyJess()).setCollection(ItemCollection.HALLOWEEN));
        register(95, (new JackTheGhost()).setCollection(ItemCollection.HALLOWEEN));
        register(91, (new InfectedPet()).setCollection(ItemCollection.HALLOWEEN));
        register(90, (new WitchPet()).setCollection(ItemCollection.HALLOWEEN));
        register(89, (new ClownInBox()).setCollection(ItemCollection.HALLOWEEN));
        register(88, (new SkeletonDragon()).setCollection(ItemCollection.HALLOWEEN));
        register(82, (new SCP049()).setCollection(ItemCollection.HALLOWEEN));
        register(81, (new PlagueBringerPet()).setCollection(ItemCollection.HALLOWEEN));
        register(40, (new PumpkinPet()).setCollection(ItemCollection.HALLOWEEN));
        register(39, (new TrumpetPet()).setCollection(ItemCollection.HALLOWEEN));
        register(38, (new BrainBasketPet()).setCollection(ItemCollection.HALLOWEEN));
        register(94, (new DeathNote()).setCollection(ItemCollection.FALL));
        register(93, (new FirstRang()).setCollection(ItemCollection.FALL));
        register(92, (new BookStack()).setCollection(ItemCollection.FALL));
        register(119, (new PiratePet()).setCollection(ItemCollection.SUMMER).setNew(true));
        register(118, (new SharkCatPet()).setCollection(ItemCollection.SUMMER).setNew(true));
        register(117, (new DragonCatPet()).setCollection(ItemCollection.SUMMER).setNew(true));
        register(116, (new BeeCatPet()).setCollection(ItemCollection.SUMMER).setNew(true));
        register(86, (new SummerBallPet()).setCollection(ItemCollection.SUMMER));
        register(85, (new IceCreamGlassPet()).setCollection(ItemCollection.SUMMER));
        register(84, (new IceBlockPet()).setCollection(ItemCollection.SUMMER));
        register(79, (new FanPet()).setCollection(ItemCollection.SUMMER));
        register(77, (new HornetPet()).setCollection(ItemCollection.SUMMER));
        register(76, (new BeePet()).setCollection(ItemCollection.SUMMER));
        register(75, (new ButterflyFlower()).setCollection(ItemCollection.SUMMER));
        register(74, (new EasterEgg("green")).setCollection(ItemCollection.EASTER));
        register(73, (new EasterEgg("blue")).setCollection(ItemCollection.EASTER));
        register(72, (new EasterEgg("red")).setCollection(ItemCollection.EASTER));
        register(71, (new EasterEgg("orange")).setCollection(ItemCollection.EASTER));
        register(70, (new EasterEgg("white")).setCollection(ItemCollection.EASTER));
        register(115, (new CopperGolem()).setCollection(ItemCollection.SPRING));
        register(114, (new SpringKeeper()).setCollection(ItemCollection.SPRING));
        register(113, (new FrogPet("tropical")).setCollection(ItemCollection.SPRING));
        register(112, (new FrogPet("frost")).setCollection(ItemCollection.SPRING));
        register(111, (new FrogPet("default")).setCollection(ItemCollection.SPRING));
        register(80, (new PancakesPlate()).setCollection(ItemCollection.SPRING));
        register(110, (new GrinchPet()).setCollection(ItemCollection.WINTER).setNew(true));
        register(109, (new SnowMaiden()).setCollection(ItemCollection.WINTER).setNew(true));
        register(108, (new GrandFatherFrost()).setCollection(ItemCollection.WINTER).setNew(true));
        register(107, (new Cryogen()).setCollection(ItemCollection.WINTER).setNew(true));
        register(106, (new PenguinPet()).setCollection(ItemCollection.WINTER).setNew(true));
        register(105, (new Iceologer()).setCollection(ItemCollection.WINTER).setNew(true));
        register(83, (new SnowManPet()).setCollection(ItemCollection.WINTER));
        register(78, (new FoxPet("snow")).setCollection(ItemCollection.WINTER));
        register(54, (new CupPet("green")).setCollection(ItemCollection.WINTER));
        register(53, (new CupPet("red")).setCollection(ItemCollection.WINTER));
        register(52, (new CupPet("blue")).setCollection(ItemCollection.WINTER));
        register(51, (new CupPet("yellow")).setCollection(ItemCollection.WINTER));
        register(50, (new GiftBig()).setCollection(ItemCollection.WINTER));
        register(19, (new Mandarin()).setCollection(ItemCollection.WINTER));
        register(20, (new SledPet()).setCollection(ItemCollection.WINTER));
        register(21, (new ElfPet()).setCollection(ItemCollection.WINTER));
        register(22, (new SprucePet()).setCollection(ItemCollection.WINTER));
        register(23, (new XmasGiftPet("red")).setCollection(ItemCollection.WINTER));
        register(24, (new XmasGiftPet("blue")).setCollection(ItemCollection.WINTER));
        register(25, (new XmasGiftPet("green")).setCollection(ItemCollection.WINTER));
        register(26, (new XmasGiftPet("yellow")).setCollection(ItemCollection.WINTER));
        register(9, (new ChestPet("red")).setCollection(ItemCollection.WINTER));
        register(10, (new ChestPet("green")).setCollection(ItemCollection.WINTER));
        register(40154, (new NootNootPet()).setNew(true));
        register(40153, (new RamenPet()).setNew(true));
        register(40152, (new PufferFishPet()).setNew(true));
        register(40151, (new PhasmophobiaNotebook()).setNew(true));
        register(40150, (new MegaBox()).setNew(true));
        register(40149, (new VPlushie()).setNew(true));
        register(40148, (new NPlushie()).setNew(true));
        register(40147, (new JPlushie()).setNew(true));
        register(40146, (new GhostFoxPet()).setNew(true));
        register(40145, (new DragonPet("aqua")).setNew(true));
        register(40144, (new DragonPet("gold")).setNew(true));
        register(40143, (new DragonPet("red")).setNew(true));
        register(40142, (new DragonPet("white")).setNew(true));
        register(40141, new WallE());
        register(40140, new HollowKnight());
        register(40139, new HuggyWuggy("kissymissy"));
        register(40138, new HuggyWuggy("huggywuggy"));
        register(40137, new CrystalMaiden());
        register(40136, new FatNuggets());
        register(40135, new WardenPet());
        register(40134, new WumpusPet());
        register(40133, new MusicBox());
        register(40132, new AppaPet());
        register(40131, new ArcadeMachine());
        register(40130, new CeaslessVoid());
        register(40129, new GrisSkelly());
        register(40128, new RaccoonPet());
        register(40127, new ProvidencePet());
        register(40126, new FallGuy());
        register(40125, new AtomPet());
        register(40124, new AxolotlBucket());
        register(40123, new KleeBomb());
        register(40121, new MysteryBlock());
        register(40120, new CupheadPet());
        register(40119, new MugmanPet());
        register(40118, new FlowerPet("ice"));
        register(40117, new FlowerPet("flame"));
        register(40116, new PipePet());
        register(40115, new PopItPet());
        register(40114, new Microphone("yellow"));
        register(40113, new Microphone("blue"));
        register(40112, new Microphone("green"));
        register(40111, new Microphone("red"));
        register(40110, new JoJoReference());
        register(40109, new MaskAkuAkuPet());
        register(40108, new JudgmentTurtlePet());
        register(40107, new AxolotlPet());
        register(40106, new TractorPet());
        register(40105, new TeaCup());
        register(40104, new SandGlass());
        register(40103, new SCP500());
        register(40102, new RoyalAnvil());
        register(40101, new PredatorPet());
        register(40100, new MarioMushroom("green"));
        register(40099, new MarioMushroom("red"));
        register(40098, new AnglerFish());
        register(40097, new ToyStoryAlienPet());
        register(40096, new SignusPet());
        register(40095, new BoscoPet());
        register(40087, new PuppyBoxPet());
        register(40122, new KittenFishingPet());
        register(40094, new HoglinPet());
        register(40093, new CosmonautPet("red"));
        register(40092, new CosmonautPet("yellow"));
        register(40091, new CosmonautPet("green"));
        register(40090, new CosmonautPet("blue"));
        register(40089, new PandaPet());
        register(40088, new FoxPet("default"));
        register(40086, new EasterCake());
        register(40085, new EasterBunny());
        register(40084, new EasterChicken());
        register(40083, new MushroomPet("brown"));
        register(40082, new MushroomPet("red"));
        register(40081, new MushroomPet("nether_red"));
        register(40080, new MushroomPet("nether_green"));
        register(40079, new BabyYodaPet());
        register(40078, new LanternPet("blue"));
        register(40077, new LanternPet("yellow"));
        register(40076, new SheepPig());
        register(40075, new ProbiusPet("yellow"));
        register(40074, new OliviaPet());
        register(40073, new ReaperPet());
        register(40072, new CloudPet());
        register(40071, new CubeCompanion());
        register(40070, new PinataPet());
        register(40069, new DuckyPet());
        register(40068, new CatLegPet());
        register(40067, new ShavermaPet());
        register(40066, new BurgerPet());
        register(40064, new Oreo());
        register(40065, new HotDog());
        register(40001, new PersonaPet());
        register(40002, new EndermanPet());
        register(40003, new ZombiePet());
        register(40004, new SkeletonPet());
        register(40005, new CreeperPet());
        register(40006, new SlimePet());
        register(40007, new PlayerPet("SmaIK"));
        register(40008, new PlayerPet("xtrafrancyz"));
        register(40009, new PlayerPet("Okssi"));
        register(40010, new PlayerPet("Lucy"));
        register(40011, (new PlayerPet("UtyCool")).yt());
        register(40012, (new PlayerPet("MedvedYT")).yt());
        register(40038, (new PlayerPet("Minikotic")).yt());
        register(40039, (new PlayerPet("DILLERON")).yt());
        register(40040, (new PlayerPet("_Evgexa_")).yt());
        register(40041, (new PlayerPet("Teroser")).yt());
        register(40042, (new PlayerPet("SvinPlay")).yt());
        register(40044, (new PlayerPet("ZoGa")).yt());
        register(40045, (new PlayerPet("MrDioxide")).yt());
        register(40046, (new PlayerPet("EFFECT", "effect")).yt());
        register(40047, (new PlayerPet("NyanKOT")).yt());
        register(40048, (new PlayerPet("Demaster")).yt());
        register(40049, (new PlayerPet("LuckyFirst")).yt());
        register(40050, (new PlayerPet("TheNakuName")).yt());
        register(40051, (new PlayerPet("MrHald")).yt());
        register(40013, new WalrusPet());
        register(40014, new VivillonPet());
        register(40015, new BimoPet());
        register(40016, new PlayerPet("\u041a\u0435\u043d\u043d\u0438", "kenny"));
        register(40017, new BombPet());
        register(40018, new TardisPet());
        register(40019, new GhastPet());
        register(40020, new BearPet());
        register(40021, new ChestPet("normal"));
        register(40022, new ChipmunkPet());
        register(40023, new SnailPet());
        register(40024, new KodamaPet());
        register(40025, new ConsolePet());
        register(40026, new DeerPet());
        register(40027, new ChickenPet());
        register(40028, new ChickenBabyPet());
        register(40029, new WildDuckPet());
        register(40030, new UnluckyCatPet());
        register(40031, new GiftPet());
        register(40032, new BagItPet());
        register(40033, new AndroidPet());
        register(40034, new SkullPet());
        register(40035, new BookGF1Pet());
        register(40036, new BookGF2Pet());
        register(40037, new BookGF3Pet());
        register(40043, new BillPet());
        register(40052, new PokeballPet());
        register(40053, new OwlPet());
        register(40054, new PlayerPet("\u041d\u0443\u0431\u0430\u0441", "steve_noob"));
        register(40055, new Spinner("white"));
        register(40056, new Spinner("blue"));
        register(40057, new Spinner("red"));
        register(40058, new Spinner("green"));
        register(40059, new Spinner("yellow"));
        register(40060, new SpinnerFlash());
        register(40061, new CatGun());
        register(40062, new YTButton());
        register(40063, new KnucklesPet());
    }

    private static void register(int id, BaseItem item)
    {
        item.id = id;

        if (ITEMS.put(Integer.valueOf(id), item) != null)
        {
            throw new RuntimeException("Duplicate item id: " + id);
        }
    }

    public static List<BaseItem> getItems(ItemType type)
    {
        List<BaseItem> list = new ArrayList();

        for (BaseItem baseitem : ITEMS.values())
        {
            if (baseitem.getType() == type)
            {
                list.add(baseitem);
            }
        }

        return list;
    }

    static
    {
        long i = System.currentTimeMillis();

        try
        {
            init();
            MiniDot.log.info("MiniDot initialized in " + (System.currentTimeMillis() - i) + " ms. " + ITEMS.size() + " items");
        }
        catch (Exception exception)
        {
            ITEMS.clear();
            MiniDot.log.error((String)"Could not initialize MiniDot models", (Throwable)exception);
        }
    }
}
